language: go
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - master

before_script:
  - go mod download
  - go get github.com/mattn/goveralls

script:
  - make test
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
