language: go
go:
# Previous versions cannot support test command with coverprofile for multiple-packages
#  - 1.7.x
#  - 1.8.x
#  - 1.9.x
  - 1.10.x
  - 1.11.x
  - master

before_script:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - $HOME/gopath/bin/dep ensure
  - go get github.com/mattn/goveralls

script:
  - make test./...
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
