name: Actions

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.13', 'stable']
    steps:
    - uses: actions/checkout@v3
    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - run: |
        go test -cover -race -v -coverprofile=coverage.out ./... &&
        go tool cover -func coverage.out
    - uses: paambaati/codeclimate-action@v3.2.0
      if: matrix.go == 'stable' && github.event_name != 'pull_request'
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        prefix: github.com/limjcst/riviere
        coverageLocations: ${{github.workspace}}/coverage.out:gocov
