name: Actions

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.13', 'stable']
    steps:
    - uses: actions/checkout@v3
    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - run: |
        go test -cover -race -v -coverprofile=coverage.out ./...
